<a href="https://colab.research.google.com/github/VishalMCF/Python-Finance-For-Investments/blob/main/Numpy_Basics_For_Finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Numpy**

In [1]:
# prompt: import numpy

import numpy as np


**Creating Numpy Arrays**

In [2]:
# declare a python list
my_List = [1,2,3,4,5]

#create a numpy array from python list
my_array = np.array(my_List)

#print the array
print(my_array)

#print the type of the array
print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Creating Matrix**

In [4]:
#declare a python list of list of consitent mxn dimensions
my_python_matrix = [[1,2,3], [4,5,6], [7,8,9]]

#print the python list of list
print(my_python_matrix)

#print the type of the matrix created above
print(type(my_python_matrix))

#create numpy matrix from python list
my_numpy_matrix = np.array(my_python_matrix)

#print the numpy matrix
print(my_numpy_matrix)

#print the type of the numpy matrix
print(type(my_numpy_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
